config/routes.rb
Rails.application.routes.draw do
  resources :stories
  resources :writers
  resources :tag
  get '/', :to => 'home#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :stories
    has_many :writers, through: :stories 
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :writer
    belongs_to :country 
    has_many :story_tags
    has_many :tags, through: :story_tags
    accepts_nested_attributes_for :writer

    # def self.find_stories_by_writer

    # end 

end

app/models/story_tag.rb
class StoryTag < ApplicationRecord
    belongs_to :tag 
    belongs_to :story 
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :story_tags
    validates :name, presence: :true 
end

app/models/writer.rb
class Writer < ApplicationRecord
    has_many :stories
    has_many :countries, through: :stories
    has_many :tags, through: :stories 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def show

end 

end 

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    def index
        @stories = Story.all
        @countries = Country.all 
        @writers = Writer.all 
        @tags = Tag.all
    end 

    def new
        @story = Story.new 
        @tags = Tag.all 
        @writers = Writer.all 
        @countries = Country.all
    end 

    def create
        if writer_name == ""
            @story = Story.new(story_params)
            @tags = filtertags
            @story.save 
            @tags.each do |tag_id| 
                StoryTag.create(:tag_id => tag_id, :story_id => @story.id) 
            end
            redirect_to story_path(@story) 

            elsif writer_name.length > 0 
                @author = Writer.create(name: writer_name, age: writer_age) 
                @story = Story.new(story_params) 
                @story.writer_id = @author.id  
                @tags = filtertags
                @tags.each do |tag_id|
                    StoryTag.create(:tag_id => tag_id, :story_id => @story.id) 
                end
                @story.save 
                redirect_to story_path(@story)

        else  
            render :new 
        end 
    end 

    def show  
        @story = Story.find(params[:id]) 
        @writer = Writer.find(@story.writer_id) 
        @tags = @story.tags 
    end 

    def edit
        @story = Story.find(params[:id]) 
        @tags = Tag.all 
        @writers = Writer.all 
        @countries = Country.all
    end 

    def update
        @story = Story.find(params[:id])  
        @tags = filtertags 
        @tags.each do |tag_id| 
            StoryTag.create(:tag_id => tag_id, :story_id => @story.id) 
        end
        @story.update(story_params)
        redirect_to story_path(@story) 
    end 

    def destroy 
        Story.find(params[:id]).destroy
        redirect_to stories_path 
    end 

    private

    def story_params
        params.require(:story).permit(:content, :subject, :writer_id, :country_id)
    end 

    def writer_name
        params.require(:story)[:writers][:name]
    end 

    def writer_age
        params.require(:story)[:writers][:age]
    end 

    def filtertags
        params[:story][:tags].delete_if { |num| num.to_i == 0}
    end 
end

app/controllers/tag_controller.rb
class TagController < ApplicationController

def show
    @tag = Tag.find(params[:id])
    @stories = Story.all 
end 

end 

app/controllers/writers_controller.rb
class WritersController < ApplicationController

    def index
        @writers = Writer.all
    end 

    def new
        @writer = Writer.new 
    end 

    def create
        @writer = Writer.create(writer_params) 
    end 

    def show
        @writer = Writer.find(params[:id]) 
    end 

    private

    def writer_params
        params.require(:writer).permit(:name, :age)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/home/show.html.erb
<style>
* {
  text-align: center;
}
</style>
<br>
<br>
<br>
<br>
<br>
<br>
<h1>Welcome to Humans of Seattle & Beyond</h1>

<h4>Where everyone's story is worth sharing</h4>
<br>
<%= image_tag("/../../../assets/photo_montage.jpg") %>
<br>
<br>
<br>
<button>
<p><%= link_to "Enter here", stories_path%> </p>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with model: @story do |f| %>
    <p>Select your name  <%= f.collection_select :writer_id, @writers, :id, :name, {prompt: true} %></p>
    
    <p>Or enter your name:

    <%= f.fields_for :writers do |writer| %> 
        <%= writer.text_field :name %></p>
    <% end %>
    <br>
    <p>Who are you writing about? <%= f.text_field :subject %><br><br></p>

   <p> What's their story: </p>  <textarea id="styled" <%= f.text_area :content %> </textarea>
   
   <br><br>

    <p>In which country did this story happen? <%= f.collection_select :country_id, @countries, :id, :name %><br><br></p>

    <p>How would you categorize your story? <br><br></p>
        <% @tags.each do |tag| %>
           <%= f.check_box :tags, {:multiple => true}, tag.id %>
           <%= f.label tag.name %>
        <%end%>
        <br>
        <br>
    <button>
    <%= f.submit 'Create / Update', :class => 'create_update_buttons'%>
    </button>
<% end %>

app/views/stories/edit.html.erb
  <header>
      <%= link_to "Home", stories_path %>
      <%= link_to "Write a story", new_story_path %>
  </header>
  
  <h1>Edit your story</h1> 

  <%= render 'form' %>

app/views/stories/index.html.erb
  <header>
      <%= link_to "Home", stories_path %>   
      <%= link_to "Write a story", new_story_path %>
  </header>
  
<div class="left_column">
  <h3> Stories </h3>
    <% @stories.each do |story| %>
    <p> <%= link_to "#{story.subject} from #{@countries[story.country_id-1].name}", story_path(story) %></p>
  <% end %>

  <br>

  <button>
    <div class="write_your_own_story">
       <p><%= link_to "Write your own story", new_story_path%> </p>
    </div>
  </button>
  <br>
</div>

<h3> Writers </h3>
<% @writers.each do |writer| %>
    <p><%=  link_to writer.name, writer_path(writer) %></p>
<% end %>

<div class="category_banner">
  <h3> View stories by category </h3>
  <% @tags.each do |tag| %>
    <button>
      <%=  link_to tag.name.capitalize, tag_path(tag) %>
    </button>
  <% end %>
</div> 

app/views/stories/new.html.erb
<header>
      <%= link_to "Home", stories_path %>
      <%= link_to "Write a story", new_story_path %>
</header>
  
<h1>Create your own story</h1> 

<%= render 'form' %>

app/views/stories/show.html.erb
<header>
    <%= link_to "Home", stories_path %>
    <%= link_to "Write a story", new_story_path %>
</header>
  
<h1> The story </h1>

<br>

<h4>Subject:</h4> <%= @story.subject %><br><br>
<h4>Story:</h4> <div class="story_content_show_page"> <%= @story.content %></div><br>
<h4>Author:</h4> <%= @writer.name %><br><br>
<h4>Country:</h4> <%= @story.country.name %><br><br>
<h4>Tags:</h4> 
    <% @tags.each do |tag| %>
       <p> <%=tag.name %><br></p>
    <% end %>

<br>
<br>

<button>
<%= link_to "Edit", edit_story_path%> 
</button>

<button>
<%= link_to "Delete", @story, method: :delete %> 
</button> 

app/views/tag/show.html.erb
<header>
    <%= link_to "Home", stories_path %>
    <%= link_to "Write a story", new_story_path %>
</header>
  
<h1> <%= @tag.name %> stories</h1>

<br>

<% @stories.each do |story| %>
    <% story.story_tags.each do |story_tag| %>
      <% if story_tag.tag_id == @tag.id %>
          <h3><%= story.subject %></h3><br>
          <div class="story_content_show_page"><%= story.content %></div><br><br>
      <% end %>
  <% end %>
<% end %> 

app/views/writers/show.html.erb
<header>
    <%= link_to "Home", stories_path %>
    <%= link_to "Write a story", new_story_path %>
</header>
  
<h1> <%= @writer.name %> </h1>

<br>

<% @writer.stories.each do |story| %><br>
    <h4><%= story.subject %><br></h4>
  <p> <div class="story_content_show_page"> <%= story.content %></div></p>
    <br>
    <% end %>